apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: postgres-example
build:
  artifacts:
  - image: backend
    context: .
    sync:
      infer:
      - '**/*'
deploy:
  kubectl:
    manifests:
      - ./k8s/*